"use client";

import { AlertTriangle, Eye, CheckCircle2, Sparkles } from "lucide-react";
import { useTheme } from "@/components/theme/ThemeProvider";

/**
 * Both registers' wording for one line, computed together server-side (see buildInsights() /
 * buildLeadTimeInsights()) since they're cheap pure string templates over numbers already in
 * hand — never a second data fetch. Picking between them is a client-side theme read, not a
 * round trip, which is what makes toggling Gaby's View instant instead of waiting on a refetch.
 */
export type InsightText = { professional: string; gaby: string };
export type Insight = { text: InsightText; tone: "positive" | "watch" | "negative" };
export type PositiveHighlight = { label: string; detail: string };

const TONE_META: Record<Insight["tone"], { icon: typeof AlertTriangle; className: string }> = {
  negative: { icon: AlertTriangle, className: "text-red-600" },
  watch: { icon: Eye, className: "text-amber-700" },
  positive: { icon: CheckCircle2, className: "text-emerald-700" },
};

/**
 * Generic "What Should I Know?" panel, extracted from the P1 SLA page's original
 * P1InsightsPanel so every drill-down (P1 SLA, Lead Time, ...) shares one implementation. Every
 * line is generated by a report's own buildInsights()-style function from numbers already
 * computed elsewhere on the page — never free text or LLM-authored.
 *
 * A client component so it can read the theme directly instead of through a THEME_COOKIE mirror:
 * the first version of this picked the register on the SERVER, which meant toggling the theme
 * needed a `router.refresh()` (a full page data refetch, including thousands of Supabase rows)
 * just to change wording — and a naive "refresh once per mount" guard on that refresh meant a
 * SECOND toggle in the same page visit was silently ignored, so it looked like only a filter
 * change (a real navigation) ever picked up the new theme. Reading `theme` client-side sidesteps
 * both problems: no refetch, no staleness, no guard to get wrong — the register updates the
 * instant the toggle fires.
 *
 * In Gaby's View, the chosen text has a `**bold**` headline (see the "Gaby voice" spec,
 * 2026-09-02) — renderBoldSegments below is the only markdown this panel understands, on
 * purpose: it's a headline emphasis marker, not a real Markdown renderer.
 */
function renderBoldSegments(text: string) {
  const segments = text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean);
  if (segments.length === 1) return text;
  return segments.map((segment, i) =>
    segment.startsWith("**") && segment.endsWith("**") ? (
      <strong key={i} className="font-semibold text-neutral-900">
        {segment.slice(2, -2)}
      </strong>
    ) : (
      <span key={i}>{segment}</span>
    )
  );
}
export function InsightsPanel({
  insights,
  positiveHighlights,
  title = "What Should I Know?",
}: {
  insights: Insight[];
  positiveHighlights: PositiveHighlight[];
  title?: string;
}) {
  const { theme } = useTheme();
  const gaby = theme === "adhd";

  if (!insights.length && !positiveHighlights.length) return null;

  return (
    <div className="card p-5">
      <div className="flex items-center gap-1.5 mb-3">
        <Sparkles className="w-4 h-4 text-sprout-600" />
        <h3 className="text-sm font-semibold text-neutral-900">{title}</h3>
      </div>
      <ul className="space-y-2.5">
        {insights.map((insight, i) => {
          const meta = TONE_META[insight.tone];
          const Icon = meta.icon;
          return (
            <li key={i} className="flex items-start gap-2 text-sm text-neutral-700">
              <Icon className={`w-4 h-4 shrink-0 mt-0.5 ${meta.className}`} />
              <span>{renderBoldSegments(gaby ? insight.text.gaby : insight.text.professional)}</span>
            </li>
          );
        })}
      </ul>

      {positiveHighlights.length > 0 && (
        <div className="mt-4 pt-4 border-t border-neutral-100">
          <p className="text-xs font-medium text-neutral-500 uppercase tracking-wide mb-2">What&apos;s Going Well</p>
          <ul className="space-y-1.5">
            {positiveHighlights.map((h, i) => (
              <li key={i} className="text-xs text-neutral-500">
                <span className="font-medium text-emerald-700">{h.label}:</span> {h.detail}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
