import { AlertTriangle, Eye, CheckCircle2, Sparkles } from "lucide-react";
import type { P1Insight, P1PositiveHighlight } from "@/lib/p1-sla";

const TONE_META: Record<P1Insight["tone"], { icon: typeof AlertTriangle; className: string }> = {
  negative: { icon: AlertTriangle, className: "text-red-600" },
  watch: { icon: Eye, className: "text-amber-700" },
  positive: { icon: CheckCircle2, className: "text-emerald-700" },
};

/**
 * "What Should I Know?" — every line here is generated by buildInsights() in lib/p1-sla.ts from
 * numbers already computed elsewhere on this page (compliance delta, top delay reason, cross-team
 * share, recurring pattern, at-risk count). Nothing here is free text or LLM-authored, and a rule
 * only emits a line when its specific condition is true — see that function for the exact rules.
 */
export function P1InsightsPanel({ insights, positiveHighlights }: { insights: P1Insight[]; positiveHighlights: P1PositiveHighlight[] }) {
  if (!insights.length && !positiveHighlights.length) return null;

  return (
    <div className="card p-5">
      <div className="flex items-center gap-1.5 mb-3">
        <Sparkles className="w-4 h-4 text-sprout-600" />
        <h3 className="text-sm font-semibold text-neutral-900">What Should I Know?</h3>
      </div>
      <ul className="space-y-2.5">
        {insights.map((insight, i) => {
          const meta = TONE_META[insight.tone];
          const Icon = meta.icon;
          return (
            <li key={i} className="flex items-start gap-2 text-sm text-neutral-700">
              <Icon className={`w-4 h-4 shrink-0 mt-0.5 ${meta.className}`} />
              <span>{insight.text}</span>
            </li>
          );
        })}
      </ul>

      {positiveHighlights.length > 0 && (
        <div className="mt-4 pt-4 border-t border-neutral-100">
          <p className="text-xs font-medium text-neutral-500 uppercase tracking-wide mb-2">What&apos;s Going Well</p>
          <ul className="space-y-1.5">
            {positiveHighlights.map((h, i) => (
              <li key={i} className="text-xs text-neutral-500">
                <span className="font-medium text-emerald-700">{h.label}:</span> {h.detail}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
