import type { P1Insight, P1PositiveHighlight } from "@/lib/p1-sla";
import { InsightsPanel } from "@/components/dashboard/InsightsPanel";

/**
 * "What Should I Know?" — every line here is generated by buildInsights() in lib/p1-sla.ts from
 * numbers already computed elsewhere on this page (compliance delta, top delay reason, cross-team
 * share, recurring pattern, at-risk count). Nothing here is free text or LLM-authored, and a rule
 * only emits a line when its specific condition is true — see that function for the exact rules.
 * Thin P1-typed wrapper around the shared InsightsPanel (also used by the Lead Time deep-dive).
 */
export function P1InsightsPanel({ insights, positiveHighlights }: { insights: P1Insight[]; positiveHighlights: P1PositiveHighlight[] }) {
  return <InsightsPanel insights={insights} positiveHighlights={positiveHighlights} />;
}
